name: likeminds_feed_example
description: Master sample app for LikeMinds Feed SDK
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  overlay_support: any
  cupertino_icons: ^1.0.2
  flutter_svg:
  dotenv: ^4.2.0
  likeminds_feed_flutter_core:
  likeminds_feed: # 1.6.3
    path: ../../LikeMinds-Flutter-Feed-SDK
  likeminds_feed_flutter_ui:
  flutter_notification_channel: ^2.0.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  device_info_plus:
  uni_links:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
