name: likeminds_feed_sample
description: Master sample app for LikeMinds Feed SDK
publish_to: "none"

version: 1.6.1

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg:
  dotenv: ^4.2.0
  likeminds_feed_flutter_core: 1.6.1
  flutter_notification_channel: ^2.0.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  uni_links:
  envied: ^0.5.4+1
  flutter_dotenv:
  timeago: ^3.6.1
  overlay_support: 
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  envied_generator:
  build_runner:

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/qna/icons/
    - assets/social_dark/icons/
    - .env
