name: likeminds_feed_sample
description: Master sample app for LikeMinds Feed SDK
publish_to: "none"

version: 1.4.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg:
  dotenv: ^4.2.0
  likeminds_feed_flutter_core: 1.4.1
  flutter_notification_channel: ^2.0.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  device_info_plus: ^8.2.2
  uni_links:
  envied: ^0.3.0+3
  flutter_dotenv:

dependency_overrides:
  extended_text_field: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  envied_generator:
  build_runner:

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - .env
