name: likeminds_feed_flutter

packages:
  - packages/*
  - example/
  - example_video_feed/

scripts:
  analyze:
    exec: dart analyze .

  clean:
    exec: flutter clean .

  dry-run:
    exec: flutter pub publish --dry-run

  test:packages:
    run: |
      cd example
      cp pubspec_overrides_3_19.yaml pubspec_overrides.yaml
      fvm use 3.19.0
      fvm flutter clean
      fvm flutter pub get
      cp pubspec_overrides_3_22.yaml pubspec_overrides.yaml
      fvm use 3.22.0
      fvm flutter clean
      fvm flutter pub get
      cp pubspec_overrides_3_24.yaml pubspec_overrides.yaml
      fvm use 3.24.0
      fvm flutter clean
      fvm flutter pub get

  build:example:
    run: |
      cd example
      fvm flutter clean
      fvm flutter pub get
      fvm flutter build apk
      cd ios
      pod update
      pod deintegrate
      pod install --repo-update
      cd ..
      fvm flutter build xcarchive
      fvm flutter build web
    description: Build the example app for all platforms.

  build:all-versions:
    run: |
      cd example
      cp pubspec_overrides_3_19.yaml pubspec_overrides.yaml
      fvm use 3.19.0
      melos build:example
      cp pubspec_overrides_3_22.yaml pubspec_overrides.yaml
      fvm use 3.22.0
      melos build:example
      cp pubspec_overrides_3_24.yaml pubspec_overrides.yaml
      fvm use 3.24.0
      melos build:example
      cp pubspec_overrides_3_22.yaml pubspec_overrides.yaml
    description: Build the example app for all platforms.

  upgrade: 
    exec: flutter pub upgrade

