name: likeminds_feed_flutter

packages:
  - packages/*
  - example/

scripts:
  analyze:
    exec: dart analyze .

  clean:
    exec: flutter clean .

  dry-run:
    exec: flutter pub publish --dry-run

  build:example:
    run: |
      cd example
      flutter clean
      flutter pub get
      flutter build apk
      flutter build xcarchive
      flutter build web
    description: Build the example app for all platforms.


  upgrade: 
    exec: flutter pub upgrade

