name: likeminds_feed_flutter
description: Monorepo workspace for managing LikeMinds Feed Flutter packages
homepage: https://likeminds.community

environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  melos: ^3.0.1
