name: likeminds_feed_flutter_core
description: Core package of LikeMinds Feed Flutter SDK, provides access to screens, BLoCs, and other utilities.
version: 1.6.1
homepage: "https://www.likeminds.community/"

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  device_info_plus: ^9.0.0
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  share_plus: ^7.2.2
  likeminds_feed: 1.12.0
  amazon_cognito_identity_dart_2: ^3.6.0
  overlay_support: ^2.1.0
  video_player: ^2.7.2
  path: ^1.8.3
  infinite_scroll_pagination: ^4.0.0
  collection: ^1.17.0
  permission_handler: ^10.4.5
  file_picker: ^5.3.1
  custom_pop_up_menu: ^1.2.4
  media_kit: ^1.1.10 # Primary package
  media_kit_video: ^1.2.4 # For video rendering.
  media_kit_libs_video: ^1.0.4
  flutter_keyboard_visibility: ^5.4.1
  extended_text_field: ^12.0.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  likeminds_feed_flutter_ui: 1.6.1
  url_launcher: ^6.1.14
  envied: ^0.3.0+3
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  async: ^2.6.0
  video_compress: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
