name: likeminds_feed_flutter_core
description: Core package of LikeMinds Feed Flutter SDK, provides access to screens, BLoCs, and other utilities.
version: 1.0.1
publish_to: "none"
homepage: "https://www.likeminds.community/"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  share_plus: ^7.2.2
  likeminds_feed: # ^1.7.0
    path: ../../../LikeMinds-Flutter-Feed-SDK
  simple_s3: ^0.3.2
  overlay_support: ^2.1.0
  video_player: ^2.7.2
  path: ^1.8.3
  infinite_scroll_pagination: ^4.0.0
  shared_preferences: ^2.2.2
  dotenv: ^4.2.0
  collection: ^1.18.0
  permission_handler: ^11.2.0
  file_picker: ^6.1.1
  device_info_plus: ^9.1.2
  http: ^1.0.0
  custom_pop_up_menu: ^1.2.4
  media_kit: ^1.1.10 # Primary package.
  media_kit_video: ^1.2.4 # For video rendering.
  media_kit_libs_video: ^1.0.4
  flutter_keyboard_visibility: ^6.0.0
  extended_text_field: ^12.1.0
  flutter_notification_channel: ^2.0.0
  firebase_core: ^2.25.3
  firebase_messaging: ^14.7.14
  likeminds_feed_flutter_ui: ^1.0.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
