name: likeminds_feed_flutter_core
description: Core package of LikeMinds Feed Flutter SDK, provides access to screens, BLoCs, and other utilities.
version: 1.4.2
homepage: "https://www.likeminds.community/"

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  share_plus: ^7.2.2
  likeminds_feed: 1.10.2
  simple_s3: ^0.3.2
  overlay_support: ^2.1.0
  video_player: ^2.7.2
  path: ^1.8.3
  infinite_scroll_pagination: ^4.0.0
  shared_preferences: ^2.2.2
  dotenv: ^4.2.0
  collection: ^1.17.0
  permission_handler: ^10.4.5
  file_picker: ^5.3.1
  device_info_plus: ^8.2.2
  http: ^1.0.0
  custom_pop_up_menu: ^1.2.4
  media_kit: ^1.1.10 # Primary package
  media_kit_video: ^1.2.4 # For video rendering.
  media_kit_libs_video: ^1.0.4
  flutter_keyboard_visibility: ^5.4.1
  extended_text_field: ^12.0.1
  flutter_notification_channel: ^2.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  likeminds_feed_flutter_ui: 1.4.2
  url_launcher: ^6.1.14
  envied: ^0.3.0+3
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  meta: ^1.9.1
  async: ^2.6.0
  video_compress: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
