// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:likeminds_feed_sample/credentials/credentials.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: FirebaseCreds.webApiKey,
    appId: FirebaseCreds.webAppId,
    messagingSenderId: FirebaseCreds.messagingSenderId,
    projectId: FirebaseCreds.projectId,
    authDomain: FirebaseCreds.authDomain,
    storageBucket: FirebaseCreds.storageBucket,
    measurementId: FirebaseCreds.measurementId,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: FirebaseCreds.androidApiKey,
    appId: FirebaseCreds.androidAppId,
    messagingSenderId: FirebaseCreds.messagingSenderId,
    projectId: FirebaseCreds.projectId,
    storageBucket: FirebaseCreds.storageBucket,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: FirebaseCreds.iosApiKey,
    appId: FirebaseCreds.iosAppId,
    messagingSenderId: FirebaseCreds.messagingSenderId,
    projectId: FirebaseCreds.projectId,
    storageBucket: FirebaseCreds.storageBucket,
    iosClientId: FirebaseCreds.iosClientId,
    iosBundleId: FirebaseCreds.iosBundleId,
  );
}
