name: likeminds_feed_flutter_ui
description: A Flutter package for Likeminds Feed UI widgets. Used alongside the Likeminds Feed SDK package (likeminds_feed) to build custom interfaces.
version: 1.9.2
homepage: "https://www.likeminds.community/"

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  collection: ^1.17.0
  path: ^1.8.3
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  visibility_detector: ^0.4.0+2
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.10+1
  media_kit: ^1.1.10 # Primary package.
  media_kit_video: ^1.2.4 # For video rendering.
  media_kit_libs_video: ^1.0.4
  visibility_aware_state: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
